services:
  # AdGuard Home
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ${APPS}/adguardhome/work:/opt/adguardhome/work
      - ${APPS}/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - proxy_network
    labels:
      - homepage.group=Infra
      - homepage.name=AdGuard Home
      - homepage.icon=sh-adguard-home
      - homepage.href=http://adguard.${HOST}
      - homepage.description=AdGuard eliminates ads, tracking, and malware
      - homepage.widget.type=adguard
      - homepage.widget.url=http://adguard.${HOST}
      - homepage.widget.username=${USER}
      - homepage.widget.password=${PASS}
      - traefik.http.services.adguard.loadBalancer.server.port=80

networks:
  proxy_network:
    driver: bridge
    external:
      name: proxy_network
