services:
  # Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS}/sonarr/config:/config
      - ${DATA}/Media/TV Shows:/tv
      - ${DATA}/Downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - proxy_network
    restart: unless-stopped
    labels:
      - homepage.group=Services
      - homepage.name=Sonarr
      - homepage.icon=si-sonarr
      - homepage.href=http://sonarr.${HOST}
      - homepage.description=An internet PVR for Usenet and Torrents.
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr.${HOST}
      - homepage.widget.key=${SONARR_KEY}
      - traefik.http.services.sonarr.loadBalancer.server.port=8989

  # Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS}/radarr/config:/config
      - ${DATA}/Media/Movies:/movies
      - ${DATA}/Downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - proxy_network
    restart: unless-stopped
    labels:
      - homepage.group=Services
      - homepage.name=Radarr
      - homepage.icon=si-radarr
      - homepage.href=http://radarr.${HOST}
      - homepage.description=See all your upcoming movies in one convenient location.
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr.${HOST}
      - homepage.widget.key=${RADARR_KEY}
      - traefik.http.services.radarr.loadBalancer.server.port=7878

  # Lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS}/lidarr/config:/config
      - ${DATA}/Media/Music:/music
      - ${DATA}/Downloads:/downloads
    ports:
      - 8686:8686
    networks:
      - proxy_network
    restart: unless-stopped
    labels:
      - homepage.group=Services
      - homepage.name=Lidarr
      - homepage.icon=si-lidarr
      - homepage.href=http://lidarr.${HOST}
      - homepage.description=A music collection manager for Usenet and BitTorrent users.
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://lidarr.${HOST}
      - homepage.widget.key=${LIDARR_KEY}
      - traefik.http.services.lidarr.loadBalancer.server.port=8686

  # Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - proxy_network
    labels:
      - homepage.group=Services
      - homepage.name=Prowlarr
      - homepage.icon=si-prowlarr
      - homepage.href=http://prowlarr.${HOST}
      - homepage.description=The Ultimate Indexer Manager.
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr.${HOST}
      - homepage.widget.key=${PROWLARR_KEY}
      - traefik.http.services.prowlarr.loadBalancer.server.port=9696

  # Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ${APPS}/bazarr/config:/config
      - ${DATA}/Media/Movies:/movies
      - ${DATA}/Media/TV Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - proxy_network
    labels:
      - homepage.group=Services
      - homepage.name=Bazarr
      - homepage.icon=si-bazarr
      - homepage.href=http://bazarr.${HOST}
      - homepage.description=A companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr.${HOST}
      - homepage.widget.key=${BAZARR_KEY}
      - traefik.http.services.bazarr.loadBalancer.server.port=6767

networks:
  proxy_network:
    driver: bridge
    name: proxy_network
