services:
  # Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS}/sonarr/config:/config
      - ${DATA}/Media/TV Shows:/tv
      - ${DATA}/Downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - proxy_network
    restart: unless-stopped

  # Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APPS}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
    name: proxy_network
