services:
  # Homepage
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    volumes:
      - ${APPS}/homepage/config:/app/config
      - ${DATA}:/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_VAR_OMV_HOST=${HOST}
      - HOMEPAGE_VAR_OMV_ADDR=${ADDR}
      - HOMEPAGE_VAR_OMV_PASS=${PASS}
    networks:
      - proxy_network
    restart: unless-stopped
    labels:
      - traefik.http.services.homepage.loadBalancer.server.port=3000
      - traefik.http.routers.homepage.rule=Host(`${HOST}`)

networks:
  proxy_network:
    driver: bridge
    external:
      name: proxy_network
